# Generated by Django 4.2.2 on 2023-10-10 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0003_cadastro_is_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='cpf_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
