# Generated by Django 4.2.2 on 2023-10-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0004_alter_cadastro_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='bairro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
