# Generated by Django 5.0.1 on 2024-02-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0006_alter_cadastro_cep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
