# Generated by Django 5.0.1 on 2024-02-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0007_alter_cadastro_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='activation_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
