# Generated by Django 5.0.1 on 2024-02-04 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_authentication', '0008_cadastro_activation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='activation_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
