# Generated by Django 4.2.2 on 2023-09-19 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_payment', models.IntegerField(verbose_name=50)),
                ('date_created', models.DateTimeField()),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_last_updated', models.DateTimeField()),
                ('status_payment', models.CharField(max_length=20)),
                ('status_detail', models.CharField(max_length=100)),
                ('payment_type_id', models.CharField(max_length=15)),
                ('payment_method_id', models.CharField(blank=True, max_length=10, null=True)),
                ('installments', models.IntegerField()),
                ('products', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
            },
        ),
    ]
