# Generated by Django 5.0.1 on 2024-02-15 03:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_payment', models.IntegerField(unique=True)),
                ('products', models.JSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_last_updated', models.DateTimeField(blank=True, null=True)),
                ('status_payment', models.CharField(max_length=20)),
                ('status_detail', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_type_id', models.CharField(blank=True, max_length=15, null=True)),
                ('interest_free_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('interest_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('installments', models.IntegerField(blank=True, null=True)),
                ('installments_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments',
                'unique_together': {('id_payment',)},
            },
        ),
    ]
