# Generated by Django 4.2.2 on 2023-10-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='products',
            new_name='products_id',
        ),
    ]
