# Generated by Django 5.0.1 on 2024-02-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payments',
            name='txid_pix',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together={('id_payment', 'txid_pix')},
        ),
    ]
