# Generated by Django 5.0.1 on 2024-02-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0002_alter_payments_unique_together_payments_txid_pix_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='txid_pix',
            new_name='txid_payment_token',
        ),
        migrations.AlterUniqueTogether(
            name='payments',
            unique_together={('id_payment', 'txid_payment_token')},
        ),
    ]
