# Generated by Django 4.2.2 on 2023-10-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0002_rename_products_payments_products_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='products_id',
        ),
        migrations.AddField(
            model_name='payments',
            name='id_cart',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
