# Generated by Django 4.2.2 on 2023-10-16 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0004_alter_payments_id_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='id_cart',
        ),
        migrations.AddField(
            model_name='payments',
            name='procucts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
