# Generated by Django 4.2.2 on 2023-10-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_payment', '0005_remove_payments_id_cart_payments_procucts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='procucts',
            new_name='products',
        ),
    ]
