# Generated by Django 4.2.2 on 2023-06-18 03:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_conversa', models.CharField(max_length=100)),
                ('data_conversa', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'conversa',
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id_destinario', models.CharField(max_length=30, unique=True)),
                ('numero_telefone', models.CharField(max_length=20, unique=True)),
                ('nome_destinatario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'destinatario',
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(max_length=100)),
                ('conteudo', models.TextField()),
                ('id_mensagem_whatsapp', models.CharField(blank=True, max_length=100, null=True)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('timestamp_whatsapp', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('recebida', 'Recebida'), ('enviada', 'Enviada'), ('modelo', 'Modelo')], max_length=10)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_whats.conversa')),
            ],
            options={
                'db_table': 'mensagens',
                'ordering': ['data_envio'],
            },
        ),
        migrations.AddField(
            model_name='conversa',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_whats.destinatario'),
        ),
        migrations.AddField(
            model_name='conversa',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
