# Generated by Django 4.2.2 on 2023-06-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinatario',
            name='wa_id_destinario',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
