# Generated by Django 4.2.2 on 2023-06-18 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0002_alter_destinatario_wa_id_destinario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensagem',
            name='id_mensagem_whatsapp',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='remetente',
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='timestamp_whatsapp',
        ),
    ]
