# Generated by Django 4.2.2 on 2023-06-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0003_remove_mensagem_id_mensagem_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversa',
            name='status_room',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
