# Generated by Django 4.2.2 on 2023-06-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0004_conversa_status_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversa',
            name='status_room',
            field=models.CharField(max_length=50),
        ),
    ]
