# Generated by Django 4.2.2 on 2023-06-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0005_alter_conversa_status_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='status_message',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mensagem',
            name='wa_id_message',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='tipo',
            field=models.CharField(choices=[('recebida', 'Recebida'), ('enviada', 'Enviada'), ('modelo', 'Modelo'), ('finalizado', 'Finalizado')], max_length=10),
        ),
    ]
