# Generated by Django 4.2.2 on 2023-06-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0008_alter_mensagem_wa_id_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='wa_id_message',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
