# Generated by Django 4.2.2 on 2023-06-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0009_alter_mensagem_wa_id_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['data_hora_message']},
        ),
        migrations.RemoveField(
            model_name='mensagem',
            name='data_envio',
        ),
        migrations.AddField(
            model_name='mensagem',
            name='data_hora_message',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
