# Generated by Django 4.2.2 on 2023-06-25 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0010_alter_mensagem_options_remove_mensagem_data_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files_WhatsApp_Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_message', models.FileField(upload_to='files_upload_whats')),
                ('file_type', models.CharField(max_length=20)),
                ('file_size', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'arquivos_mensagens',
            },
        ),
        migrations.AddField(
            model_name='mensagem',
            name='files',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_whats.files_whatsapp_message'),
            preserve_default=False,
        ),
    ]
