# Generated by Django 4.2.2 on 2023-06-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0011_files_whatsapp_message_mensagem_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files_whatsapp_message',
            name='file_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='files_whatsapp_message',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_whats.files_whatsapp_message'),
        ),
    ]
