# Generated by Django 4.2.2 on 2023-06-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0012_alter_files_whatsapp_message_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files_whatsapp_message',
            name='file_id_whatsapp',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
