# Generated by Django 4.2.2 on 2023-08-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_whats', '0018_conversa_canal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinatario',
            old_name='wa_id_destinario',
            new_name='whatsapp_id',
        ),
        migrations.RemoveField(
            model_name='destinatario',
            name='numero_telefone',
        ),
        migrations.AddField(
            model_name='destinatario',
            name='numero_telefone_telegram',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='numero_telefone_whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='destinatario',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
