# Generated by Django 4.2.2 on 2023-10-16 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0002_itemcarrinho_valor_unitário'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemcarrinho',
            old_name='valor_unitário',
            new_name='valor_unitario',
        ),
    ]
