# Generated by Django 5.0.1 on 2024-02-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_cart', '0004_carrinho_total_alter_carrinho_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcarrinho',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
